<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise.all(race)</title>
</head>

<body>
    <script>
        const PENDING = 'PENDING'
        const FULFILLED = 'FULFILLED'
        const REJECTED = 'REJECTED'
        class MyPromise {
            constructor(executor) {
                this.status = PENDING
                this.reason = null
                this.value = null
                this.fulFilledCbs = []
                this.rejectedCbs = []
                try {
                    executor(this._resolve, this._reject)
                } catch (err) {
                    this._reject(err)
                }
            }
            _resolve = (data) => {
                if (this.status === PENDING) {
                    this.status = FULFILLED
                    this.value = data
                        // this.fulFilledCbs.forEach(fn => fn(data))
                    this.fulFilledCbs.forEach(fn => fn())
                    this.rejectedCbs.forEach(fn => fn())
                }
            }
            _reject = (reason) => {
                if (this.status === PENDING) {
                    this.status = REJECTED
                    this.reason = reason
                }
            }
            then(onFulFilled, onRejected) {
                if (this.status === FULFILLED) {
                    onFulFilled(this.value)
                }
                if (this.status === REJECTED) {
                    onRejected(this.reason)
                }
                if (this.status === PENDING) {
                    // this.fulFilledCbs.push(onFulFilled)
                    this.fulFilledCbs.push(() => onFulFilled(this.value))
                    this.rejectedCbs.push(() => onRejected(this.reason))
                }
            }
            all(arr) {
                if (!Array.isArray(arr)) {
                    const type = typeof values;
                    return new TypeError(`TypeError: ${type} ${values} is not iterable`)
                }
                return new MyPromise((resolve, reject) => {
                    let resultArr = []
                    let oldIndex = 0
                    const processResultByKey = (value, index) => {
                        resultArr[index] = value
                        if (++oldIndex === arr.length) {
                            resolve(resultArr)
                        }
                    }
                    for (let i = 0; i < arr.length; i++) {
                        let value = arr[i]
                        if (value && typeof value.then === 'function') {
                            value.then((val) => {
                                processResultByKey(val, i)
                            }, reject)
                        } else {
                            processResultByKey(value, i)
                        }
                    }
                })
            }
        }

        // 测试myPromise
        // let p = new MyPromise((resolve, reject) => {
        //     setTimeout(() => { // 异步
        //             resolve('ok')
        //         })
        //         // resolve('ok') // 同步
        // })

        // p.then(res => {
        //     console.log(res)
        // }, err => {
        //     console.log(err)
        // })

        // 测试myPromise all
        // let p1 = new MyPromise((resolve, reject) => {
        //     // setTimeout(() => {
        //     resolve('ok1');
        //     // }, 1000);
        // })
        // let p2 = new MyPromise((resolve, reject) => {
        //     // setTimeout(() => {
        //     resolve('ok2');
        //     // }, 1000);
        // })
        // new MyPromise().all([1, 3, 5, p1, p2]).then(data => {
        //     console.log(data)
        // }, err => {
        //     console.log(err)
        // })

        let p1 = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('ok1');
            }, 1000);
        })
        let p2 = new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve('ok2');
                }, 2000);
            })
            // promise all
        Promise.all([1, 3, p1, 5, p2]).then(data => {
            console.log(data)
        }, err => {
            console.log(err)
        })

        Promise.all = (arr) => {
            if (!Array.isArray(arr)) {
                console.log('arr is not array....')
            }
            let resultArr = []
            let oldIdx = 0
            return new Promise((resolve, reject) => {
                const setValue = (value, idx) => {
                    resultArr.push(value)
                    if (++oldIdx === arr.length) {
                        resolve(resultArr)
                    }
                }
                for (let p in arr) {
                    if (arr[p] && arr[p].then === 'function') {
                        arr[p].then(value => {
                            setValue(value, p)
                        }, reject)
                    } else {
                        setValue(arr[p], p)
                    }
                }
            })
        }

        // promise race //  用来处理多个请求，采用最快的（谁先完成用谁的）
        Promise.race = (arr) => {
            if (!Array.isArray(arr)) {
                return arr
            }
            return new Promise((resolve, reject) => {
                for (let i = 0; i < arr.length; i++) {
                    let value = arr[i]
                    if (value && typeof value.then === 'function') {
                        value.then(resolve, reject)
                    } else {
                        resolve(value)
                    }
                }
            })
        }

        Promise.race([p2, p1, 5]).then(data => {
            console.log(data)
        }, err => {
            console.log(err)
        })

        /**
         * 特别需要注意的是：因为Promise是没有中断方法的，xhr.abort()、ajax 有自己的中断方法，
         * axios 是基于 ajax 实现的；fetch 基于 promise，所以他的请求是无法中断的。
         * 这也是 promise 存在的缺陷，我们可以使用 race 来自己封装中断方法：
         **/

        function wrap(promise) {
            let abort = null
            let newPromise = new Promise((resolve, reject) => {
                abort = reject
            })
            let p = Promise.race([promise, newPromise])
            p.abort = abort
            return p
        }
        const promise = new Promise((resolve, reject) => {
            setTimeout(() => { // 模拟的接口调用 ajax 肯定有超时设置
                resolve('成功');
            }, 1000);
        });

        let newPromise = wrap(
            
        );

        setTimeout(() => {
            // 超过3秒 就算超时 应该让 proimise 走到失败态
            newPromise.abort('超时了');
        }, 3000);

        newPromise.then((data => {
            console.log('成功的结果' + data)
        })).catch(e => {
            console.log('失败的结果' + e)
        })
    </script>
</body>

</html>